

color: '#ffc670'

hertz: 300
period: 3
amplitude:
  hi: 1
  lo: .08

logging:
  version: 1
  disable_existing_loggers: True
  formatters:
    simple:
      format: '%(asctime)s: %(message)s'
    verbose:
      format: '%(asctime)s [%(levelname)s] %(module)s %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
  root:
    level: DEBUG
    handlers: [console]
